<a href="https://colab.research.google.com/github/mkaraca25/DataScience/blob/main/LinearAlgebraNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import numpy as np

In [112]:
vector_1=np.array([1,2,3,4,5,6,7,8,9,10])

In [113]:
vector_1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [114]:
vector_2=np.array([2,1,3,4,5,7,8,6,10,9])
vector_1+vector_2

array([ 3,  3,  6,  8, 10, 13, 15, 14, 19, 19])

In [115]:
Matrix_1=np.random.randint(50,size=(5,5))
Matrix_1

array([[29, 39, 43, 19, 49],
       [37, 39, 38, 35, 14],
       [17, 16, 15, 13, 30],
       [25,  0, 11,  2, 14],
       [46, 43, 31, 34, 47]])

In [116]:
Matrix_1+5

array([[34, 44, 48, 24, 54],
       [42, 44, 43, 40, 19],
       [22, 21, 20, 18, 35],
       [30,  5, 16,  7, 19],
       [51, 48, 36, 39, 52]])

In [117]:
Matrix_1*2

array([[58, 78, 86, 38, 98],
       [74, 78, 76, 70, 28],
       [34, 32, 30, 26, 60],
       [50,  0, 22,  4, 28],
       [92, 86, 62, 68, 94]])

In [118]:
Tensor_1=np.random.randint(50,size=(3,3,5))
Tensor_1

array([[[10,  9, 25, 45, 20],
        [43, 21, 35,  2, 28],
        [10, 46,  2, 34, 15]],

       [[27, 12,  4, 43, 47],
        [10, 29,  2, 43,  8],
        [20, 33, 45, 15, 33]],

       [[21, 15,  3, 26, 33],
        [32,  4, 40, 10,  4],
        [27, 42, 23, 37,  0]]])

In [119]:
print(vector_1.shape)

(10,)


In [120]:
print(Matrix_1.shape)

(5, 5)


In [121]:
print(Tensor_1.shape)

(3, 3, 5)


In [122]:
print(vector_1.size,Matrix_1.size,Tensor_1.size)

10 25 45


In [123]:
vector_1.dot(vector_2)

380

In [124]:
Matrix_1.dot(Matrix_1)

array([[5744, 5447, 5102, 4179, 5826],
       [4681, 4174, 4462, 3108, 4647],
       [3045, 2817, 2637, 2124, 3099],
       [1606, 1753, 1696, 1098, 2241],
       [6464, 5988, 5908, 4448, 6471]])

In [125]:
matrix_A=np.random.randint(10,size=(2,2))
matrix_A

array([[4, 6],
       [7, 6]])

In [126]:
matrix_B=np.matrix(np.random.randint(10,size=(2,2)))
matrix_B

matrix([[0, 0],
        [9, 6]])

In [127]:
matrix_A[0,0]

4

In [128]:
matrix_B[0,0]

0

In [129]:
matrix_C=matrix_A.dot(matrix_B)
matrix_C

matrix([[54, 36],
        [54, 36]])

In [130]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [131]:
matrix_D=np.random.randint(10,size=(4,4))
matrix_D


array([[3, 1, 7, 6],
       [9, 2, 1, 8],
       [7, 4, 0, 4],
       [1, 2, 9, 7]])

In [132]:
np.dot(matrix_D,np.identity(4))

array([[3., 1., 7., 6.],
       [9., 2., 1., 8.],
       [7., 4., 0., 4.],
       [1., 2., 9., 7.]])

In [133]:
matrix_E=np.linalg.inv(matrix_D) #Getting the inverse of the matrix
matrix_E

array([[ 0.49620253, -0.10126582,  0.11392405, -0.37468354],
       [-0.34177215, -0.11392405,  0.25316456,  0.27848101],
       [ 0.43037975, -0.18987342,  0.08860759, -0.20253165],
       [-0.52658228,  0.29113924, -0.20253165,  0.37721519]])

In [134]:
np.dot(matrix_D,matrix_E)

array([[ 1.00000000e+00,  3.33066907e-16, -1.11022302e-16,
         1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00,
         8.88178420e-16],
       [ 0.00000000e+00, -2.22044605e-16,  1.00000000e+00,
        -2.22044605e-16],
       [ 2.22044605e-16,  2.77555756e-16,  1.66533454e-16,
         1.00000000e+00]])

In [135]:
matrix_F=np.random.randint(10,size=(4,3))
matrix_G=np.random.randint(10,size=(3,4))
print(matrix_F,"\n..........\n",matrix_G)

[[6 9 9]
 [5 2 2]
 [9 5 6]
 [8 4 7]] 
..........
 [[9 2 5 7]
 [6 2 9 2]
 [7 4 9 4]]


In [136]:
np.dot(matrix_F,matrix_G)

array([[171,  66, 192,  96],
       [ 71,  22,  61,  47],
       [153,  52, 144,  97],
       [145,  52, 139,  92]])

In [137]:
vector_3=np.random.randint(1,10,4)
vector_3

array([3, 6, 2, 5])

In [138]:
np.vdot(vector_3,matrix_A)

92

In [139]:
np.matmul(matrix_A,matrix_B)

matrix([[54, 36],
        [54, 36]])

In [140]:
matrix_Det=np.matrix(np.random.randint(10,size=(2,2)))
matrix_Det

matrix([[1, 9],
        [1, 4]])

In [141]:
np.linalg.det(matrix_Det)

-4.999999999999999

In [142]:
import numexpr as ne
vector_4=np.random.randint(1,1000000,1500000)
vector_5=np.random.randint(1,1000000,1500000)

In [143]:
%%timeit -n200 -r10
vector_3=vector_4+1

200 loops, best of 10: 2.08 ms per loop


In [144]:
%%timeit -n200 -r10
vector_3=ne.evaluate("vector_4+1")


200 loops, best of 10: 2.12 ms per loop


In [145]:
%%timeit -n200 -r10
vector_6=5*vector_4+2*vector_5

200 loops, best of 10: 7.68 ms per loop


In [151]:
%%timeit -n200 -r10
vector_6=ne.evaluate("5*vector_4+2*vector_5")

200 loops, best of 10: 4.84 ms per loop
