<a href="https://colab.research.google.com/github/mkaraca25/DataScience/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NUMPY

In [2]:
import numpy as np

In [19]:
N_Array=np.array([[1,2,3],[4,5,6]])
type(N_Array)
N_Array
N_Array_1=np.array([[2,4,6],[89,8,15]])
Integers=np.array([[1,2,3,4],[5,6,7,13]])
Integers

In [21]:
Floats=np.array([0.,0.10,0.12,0.3,0.5,0.63])
Floats

array([0.  , 0.1 , 0.12, 0.3 , 0.5 , 0.63])

In [22]:
Integers.ndim

2

In [24]:
Integers.shape  #how many matrix(format)
Integers.size

8

In [25]:
for row in Integers:
  print(row)

[1 2 3 4]
[ 5  6  7 13]


In [27]:
for row in Integers.flat:  #print the matrix side by side
  print(row,end="")

123456713

In [28]:
for row in Integers.flat:
  print(row)

1
2
3
4
5
6
7
13


In [29]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [34]:
np.full((3,5),13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [36]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(3,8)

array([3, 4, 5, 6, 7])

In [38]:
np.arange(20,1,-3)

array([20, 17, 14, 11,  8,  5,  2])

In [39]:
np.linspace(0,50)

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [40]:
np.linspace(0,50,num=5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [41]:
np.arange(1,31).reshape(5,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [44]:
np.random.randint(1,20,6)

array([ 3, 10,  1,  9,  5, 11])

In [45]:
Rand_Array=np.random.randint(1,100,15)

In [46]:
Rand_Array

array([41,  9, 88, 43, 79, 23, 68, 39, 50, 90, 94, 33, 56, 83, 86])

In [48]:
Rand_Array.max()

94

In [49]:
Rand_Array.min()

9

In [50]:
Rand_Array.mean()

58.8

In [51]:
Rand_Array.std()

26.273433984413483

In [52]:
Numbers_1=np.arange(1,10,2)
Numbers_Rand=np.random.randint(1,20,5)

In [53]:
Numbers_1

array([1, 3, 5, 7, 9])

In [54]:
Numbers_Rand

array([11,  1,  7, 10, 13])

In [55]:
Numbers_1+Numbers_Rand

array([12,  4, 12, 17, 22])

In [58]:
Numbers_1*Numbers_Rand

array([ 11,   3,  35,  70, 117])

In [59]:
Numbers_1/3

array([0.33333333, 1.        , 1.66666667, 2.33333333, 3.        ])

In [60]:
Numbers_1+=5

In [61]:
Numbers_1

array([ 6,  8, 10, 12, 14])

In [62]:
Numbers_Rand+=3

In [63]:
np.sqrt(Numbers_1)

array([2.44948974, 2.82842712, 3.16227766, 3.46410162, 3.74165739])

In [64]:
s_1=np.arange(1,10,2)
s_2=np.arange(1,11,3)

In [65]:
s_1

array([1, 3, 5, 7, 9])

In [66]:
array_1=np.random.randint(1,500,15)

In [85]:
array_1

array([485, 471, 359, 338, 315,  83, 246, 345, 150,  62, 354, 171,  23,
       275, 119])

In [86]:
array_2=array_1.reshape(3,5)

In [87]:
array_2

array([[485, 471, 359, 338, 315],
       [ 83, 246, 345, 150,  62],
       [354, 171,  23, 275, 119]])

In [92]:
index_value=np.argpartition(array_1,-5)[-5:]

In [95]:
index_value

array([ 7, 10,  1,  2,  0])

In [96]:
np.sort(array_1[index_value])

array([345, 354, 359, 471, 485])

In [117]:
index_value2=np.argpartition(array_2,-3,axis=0)[-5:]

In [118]:
index_value2

array([[1, 2, 2, 1, 1],
       [0, 1, 1, 0, 0],
       [2, 0, 0, 2, 2]])

In [119]:
np.sort(array_2[index_value2])

array([[[ 62,  83, 150, 246, 345],
        [ 23, 119, 171, 275, 354],
        [ 23, 119, 171, 275, 354],
        [ 62,  83, 150, 246, 345],
        [ 62,  83, 150, 246, 345]],

       [[315, 338, 359, 471, 485],
        [ 62,  83, 150, 246, 345],
        [ 62,  83, 150, 246, 345],
        [315, 338, 359, 471, 485],
        [315, 338, 359, 471, 485]],

       [[ 23, 119, 171, 275, 354],
        [315, 338, 359, 471, 485],
        [315, 338, 359, 471, 485],
        [ 23, 119, 171, 275, 354],
        [ 23, 119, 171, 275, 354]]])

In [120]:
index_value3=np.argpartition(array_2.ravel(),-5)[-5:]

In [121]:
index_value3

array([ 7, 10,  1,  2,  0])

In [122]:
index_value

array([ 7, 10,  1,  2,  0])

In [125]:
array_1[index_value]

array([345, 354, 471, 359, 485])

In [127]:
np.allclose(array_1,array_2.ravel(),0.1)

True

In [131]:
array_3=np.array([0.12,0.17,0.24,0.29,0.33])
array_4=np.array([0.13,0.19,0.26,0.21,0.33])
np.allclose(array_3,array_4,0.1)


False

In [140]:
np.allclose(array_3,array_4,0.4)

True

In [143]:
np.clip(array_1,100,250)

array([250, 250, 250, 250, 250, 100, 246, 250, 150, 100, 250, 171, 100,
       250, 119])

In [144]:
array_1

array([485, 471, 359, 338, 315,  83, 246, 345, 150,  62, 354, 171,  23,
       275, 119])

In [145]:
np.clip(array_2,100,250)

array([[250, 250, 250, 250, 250],
       [100, 246, 250, 150, 100],
       [250, 171, 100, 250, 119]])

In [149]:
N_Array_1=np.random.randint(1,30,8)

In [150]:
N_Array_1

array([12, 23, 14, 26, 24, 17,  3, 12])

In [152]:
N_Array_1[3]

26

In [153]:
N_Array_1[2:7]

array([14, 26, 24, 17,  3])

In [154]:
N_Array_1[:3]

array([12, 23, 14])

In [155]:
N_Array_2=np.arange(1,7)

In [157]:
N_Array_2[:3]=7

In [158]:
N_Array_2

array([7, 7, 7, 4, 5, 6])

In [160]:
N_Array_3=np.random.randint(1,100,20)
N_Array_3

array([83, 11,  5, 21, 60, 25, 31,  7, 48, 71, 87, 11, 29, 97, 66, 43, 90,
        8, 35, 33])

In [163]:
N_Array_3=N_Array_3.reshape(5,4)
N_Array_3

array([[83, 11,  5, 21],
       [60, 25, 31,  7],
       [48, 71, 87, 11],
       [29, 97, 66, 43],
       [90,  8, 35, 33]])

In [165]:
N_Array_3[4][3]

33

In [166]:
N_Array_3[:2]

array([[83, 11,  5, 21],
       [60, 25, 31,  7]])

In [171]:
N_Array_3[:,2:4]

array([[ 5, 21],
       [31,  7],
       [87, 11],
       [66, 43],
       [35, 33]])

In [174]:
N_Array_3[:,(1,3)]

array([[11, 21],
       [25,  7],
       [71, 11],
       [97, 43],
       [ 8, 33]])

In [182]:
N_Array_4=np.arange(1,7)
N_Array_4_SC=N_Array_4.view()
N_Array_4_SC[3]*=7
N_Array_4_SC

array([ 1,  2,  3, 28,  5,  6])

In [190]:
N_Array_4

array([ 1,  2,  3, 28,  5,  6])

In [189]:
N_Array_4_SC

array([ 1,  2,  3, 28,  5,  6])

In [191]:
N_Array_4_SC[2]+=5

In [192]:
N_Array_4

array([ 1,  2,  8, 28,  5,  6])

In [193]:
N_Array_4_SC

array([ 1,  2,  8, 28,  5,  6])

In [195]:
N_Array_4_DC=N_Array_4.copy()
N_Array_4_DC

array([ 1,  2,  8, 28,  5,  6])

In [196]:
N_Array_4_DC[1]-=5

In [197]:
N_Array_4_DC

array([ 1, -3,  8, 28,  5,  6])

In [198]:
N_Array_4

array([ 1,  2,  8, 28,  5,  6])

In [3]:
Array_R_1=np.random.randint(1,150,20)
Array_R_1

array([ 14, 113,   5,  72,  96,   2,  78, 142,  65, 144,  71,  41,  19,
        41,  54,  72, 142, 116,  33,  12])

In [4]:
Array_R_1.sum()

1332

In [5]:
Array_R_1.min()

2

In [6]:
Array_R_1.max()

144

In [7]:
Array_R_1.mean()

66.6

In [8]:
Array_R_1.std()

45.611840567992864

In [10]:
Array_R_2=np.arange(1,60,3)
Array_R_2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58])

In [12]:
Array_R_2+Array_R_1

array([ 15, 117,  12,  82, 109,  18,  97, 164,  90, 172, 102,  75,  56,
        81,  97, 118, 191, 168,  88,  70])

In [13]:
Array_R_1

array([ 14, 113,   5,  72,  96,   2,  78, 142,  65, 144,  71,  41,  19,
        41,  54,  72, 142, 116,  33,  12])

In [28]:
Array_R_1[10]

71

In [33]:
R_Element=Array_R_1[np.random.randint(1,21,1)]
R_Element

array([2])

In [34]:
index_value_1=np.where(Array_R_1==R_Element)
index_value_1

(array([5]),)

In [38]:
Array_R_2=Array_R_1.reshape(4,5)
Array_R_2

array([[ 14, 113,   5,  72,  96],
       [  2,  78, 142,  65, 144],
       [ 71,  41,  19,  41,  54],
       [ 72, 142, 116,  33,  12]])

In [40]:
Array_R_2[:,(1,4)]

array([[113,  96],
       [ 78, 144],
       [ 41,  54],
       [142,  12]])

In [54]:
Array_R_B=np.pad(Array_R_2,pad_width=1,mode="constant",constant_values=0)
Array_R_B

array([[  0,   0,   0,   0,   0,   0,   0],
       [  0,  14, 113,   5,  72,  96,   0],
       [  0,   2,  78, 142,  65, 144,   0],
       [  0,  71,  41,  19,  41,  54,   0],
       [  0,  72, 142, 116,  33,  12,   0],
       [  0,   0,   0,   0,   0,   0,   0]])

In [58]:
Array_R_3=np.random.randint(1,100,30)
Array_R_3=Array_R_3.reshape(6,5)
Array_R_3

array([[55, 55, 83, 84, 89],
       [56, 50, 49, 16, 87],
       [78, 71, 71, 12, 96],
       [87, 41, 85, 41, 12],
       [10, 98, 68, 63, 61],
       [ 5, 62, 66, 63, 35]])

In [59]:
Array_R_3.sort()
Array_R_3

array([[55, 55, 83, 84, 89],
       [16, 49, 50, 56, 87],
       [12, 71, 71, 78, 96],
       [12, 41, 41, 85, 87],
       [10, 61, 63, 68, 98],
       [ 5, 35, 62, 63, 66]])

In [75]:
np.put(Array_R_3,np.random.choice(range(5,6),replace=False),12)
Array_R_3

array([[55, 55, 83, 84, 89],
       [12, 49, 50, 56, 87],
       [12, 71, 71, 78, 96],
       [12, 41, 41, 85, 87],
       [10, 61, 63, 68, 98],
       [ 5, 35, 62, 63, 66]])

In [92]:
Array_5=np.arange(1,101).reshape(10,10)
Array_5

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [93]:
Array_5=np.arange(1,101).reshape(10,10)
np.put(Array_5,np.random.choice(range(5,6),replace=False),12)
Array_5

array([[  1,   2,   3,   4,   5,  12,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [94]:
Array_5[:4]

array([[ 1,  2,  3,  4,  5, 12,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40]])

In [102]:
Array_5[7:,5:]

array([[ 76,  77,  78,  79,  80],
       [ 86,  87,  88,  89,  90],
       [ 96,  97,  98,  99, 100]])

In [103]:
Array_5[2:5,4:7]

array([[25, 26, 27],
       [35, 36, 37],
       [45, 46, 47]])

In [107]:
Array_5[:,9]

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [108]:
Array_5[0,:]

array([ 1,  2,  3,  4,  5, 12,  7,  8,  9, 10])

In [120]:
Array_A=((np.random.rand(15)*10).astype(int)).reshape(3,5)
Array_A

array([[3, 5, 9, 3, 2],
       [3, 9, 2, 8, 7],
       [8, 1, 9, 2, 7]])

In [121]:
Array_B=((np.random.rand(15)*10).astype(int)).reshape(3,5)
Array_B

array([[4, 6, 3, 1, 3],
       [1, 2, 6, 3, 6],
       [1, 1, 0, 0, 4]])

In [122]:
Array_A+Array_B

array([[ 7, 11, 12,  4,  5],
       [ 4, 11,  8, 11, 13],
       [ 9,  2,  9,  2, 11]])

In [123]:
Array_A*Array_B

array([[12, 30, 27,  3,  6],
       [ 3, 18, 12, 24, 42],
       [ 8,  1,  0,  0, 28]])

In [129]:
(Array_A/Array_B).astype(int)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[                   0,                    0,                    3,
                           3,                    0],
       [                   3,                    4,                    0,
                           2,                    1],
       [                   8,                    1, -9223372036854775808,
        -9223372036854775808,                    1]])